#!/usr/local/bin/python

# Import modules.
import argparse
import time

# Define variables.
command_file = '/var/spool/icinga/rw/icinga.cmd'

# Get command line arguments.
parser = argparse.ArgumentParser(description='Write to the icinga command file.')
group = parser.add_mutually_exclusive_group()
group.add_argument('--host', action='store_true')
group.add_argument('--service', action='store_true')
parser.add_argument('--target', action='store', required=True)
parser.add_argument('--result', action='store', required=True)
parser.add_argument('--data', action='store', required=True)
args = parser.parse_args()

# Get the current time in unix seconds.
seconds = str(int(time.time()))

# Format and print the command.
if args.host:
	action = 'PROCESS_HOST_CHECK_RESULT'
else:
	action = 'PROCESS_SERVICE_CHECK_RESULT'
command = '[' + seconds + '] ' + action + ',' + target + ',' + result + ',' + data
print command

# Write the data to the icinga command file.